<a href="https://colab.research.google.com/github/srinidhibv1403/1BM23CS339-ML/blob/main/1BM23CS339_Lab_1_DataProcessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

# i. Load .csv file into the data frame
df = pd.read_csv('housing.csv')
print("CSV file loaded successfully.")
display(df.head())

In [ ]:
# ii. Display information of all columns
print("\nInformation of all columns:")
df.info()

In [ ]:
# iii. Display statistical information of all numerical columns
print("\nStatistical information of all numerical columns:")
display(df.describe())

In [ ]:
# iv. Display the count of unique labels for 'Ocean Proximity' column
print("\nCount of unique labels for 'Ocean Proximity' column:")012
display(df['ocean_proximity'].value_counts())

In [ ]:
# v. Display which attributes (columns) in a dataset have missing values count greater than zero
print("\nColumns with missing values:")
missing_values = df.isnull().sum()
columns_with_missing_values = missing_values[missing_values > 0]
if not columns_with_missing_values.empty:
    display(columns_with_missing_values)
else:
    print("No columns with missing values found.")

Diabetes Dataset

In [ ]:
import requests

url = 'https://raw.githubusercontent.com/plotly/datasets/master/diabetes.csv'
response = requests.get(url)

if response.status_code == 200:
    with open('diabetes.csv', 'wb') as f:
        f.write(response.content)
    print("Diabetes dataset downloaded successfully as 'diabetes.csv'.")
else:
    print(f"Failed to download dataset. Status code: {response.status_code}")

Diabetes dataset downloaded successfully as 'diabetes.csv'.

In [ ]:
import pandas as pd

df_diabetes = pd.read_csv('diabetes.csv')
print("Diabetes dataset loaded into df_diabetes successfully.")
display(df_diabetes.head())

Diabetes dataset loaded into df_diabetes successfully.

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [ ]:
print("1. First 5 rows of df_diabetes:")
display(df_diabetes.head())

print("\n2. Information of all columns in df_diabetes:")
df_diabetes.info()

print("\n3. Statistical information of numerical columns in df_diabetes:")
display(df_diabetes.describe())

print("\n4. Missing values in df_diabetes:")
display(df_diabetes.isnull().sum())

1. First 5 rows of df_diabetes:

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

2. Information of all columns in df_diabetes:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

3. Statistical information of numerical columns in df_diabetes:

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

4. Missing values in df_diabetes:

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [ ]:
import numpy as np

# 1. Identify columns where a value of 0 is physiologically implausible and likely represents a missing value
columns_with_potential_zeros_as_missing = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']

print("Original value counts of 0s in identified columns:")
for col in columns_with_potential_zeros_as_missing:
    if 0 in df_diabetes[col].unique():
        print(f"{col}: {df_diabetes[col].value_counts()[0]} zeros")

# 2. Replace the 0 values with NaN
for col in columns_with_potential_zeros_as_missing:
    df_diabetes[col] = df_diabetes[col].replace(0, np.nan)

print("\nAfter replacing 0s with NaN, checking for NaN counts:")
display(df_diabetes[columns_with_potential_zeros_as_missing].isnull().sum())

# 3. Impute the NaN values in these columns using the median
for col in columns_with_potential_zeros_as_missing:
    median_val = df_diabetes[col].median()
    df_diabetes[col] = df_diabetes[col].fillna(median_val)

print("\nAfter median imputation, checking for NaN counts:")
display(df_diabetes[columns_with_potential_zeros_as_missing].isnull().sum())

print("\nFirst 5 rows of df_diabetes after handling missing values:")
display(df_diabetes.head())

Original value counts of 0s in identified columns:
Glucose: 5 zeros
BloodPressure: 35 zeros
SkinThickness: 227 zeros
Insulin: 374 zeros
BMI: 11 zeros

After replacing 0s with NaN, checking for NaN counts:

Glucose            5
BloodPressure     35
SkinThickness    227
Insulin          374
BMI               11
dtype: int64

After median imputation, checking for NaN counts:

Glucose          0
BloodPressure    0
SkinThickness    0
Insulin          0
BMI              0
dtype: int64

First 5 rows of df_diabetes after handling missing values:

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.0,72.0,35.0,125.0,33.6,0.627,50,1
1,1,85.0,66.0,29.0,125.0,26.6,0.351,31,0
2,8,183.0,64.0,29.0,125.0,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1

In [ ]:
print("Handling outliers in df_diabetes...")

# 1. Identify numerical columns, excluding 'Outcome'
numerical_cols = df_diabetes.columns.drop('Outcome')

# 2-5. Calculate IQR and cap outliers for each numerical column
for col in numerical_cols:
    Q1 = df_diabetes[col].quantile(0.25)
    Q3 = df_diabetes[col].quantile(0.75)
    IQR = Q3 - Q1

    upper_bound = Q3 + 1.5 * IQR
    lower_bound = Q1 - 1.5 * IQR

    # Cap the outliers
    df_diabetes[col] = np.where(df_diabetes[col] > upper_bound, upper_bound, df_diabetes[col])
    df_diabetes[col] = np.where(df_diabetes[col] < lower_bound, lower_bound, df_diabetes[col])

print("Outliers handled successfully using IQR capping.")
print("First 5 rows of df_diabetes after outlier handling:")
display(df_diabetes.head())

Handling outliers in df_diabetes...
Outliers handled successfully using IQR capping.
First 5 rows of df_diabetes after outlier handling:

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6.0,148.0,72.0,35.0,125.000,33.6,0.627,50.0,1
1,1.0,85.0,66.0,29.0,125.000,26.6,0.351,31.0,0
2,8.0,183.0,64.0,29.0,125.000,23.3,0.672,32.0,1
3,1.0,89.0,66.0,23.0,112.875,28.1,0.167,21.0,0
4,0.0,137.0,40.0,35.0,135.875,43.1,1.200,33.0,1

In [ ]:
from sklearn.preprocessing import MinMaxScaler

print("Applying Min-Max scaling to numerical features of df_diabetes...")

# 1. Create a list of numerical columns to be scaled, excluding 'Outcome'
# The numerical_cols variable from the previous step already contains these columns.
# Re-using numerical_cols from the previous step which was df_diabetes.columns.drop('Outcome')

# 2. Instantiate the MinMaxScaler
scaler = MinMaxScaler()

# Create a temporary DataFrame for scaling to avoid modifying the original during the process, or direct scaling
# Apply Min-Max scaling to the selected numerical columns in df_diabetes using the fit_transform() method.
df_diabetes[numerical_cols] = scaler.fit_transform(df_diabetes[numerical_cols])

print("Min-Max scaling applied successfully.")
print("First 5 rows of df_diabetes after Min-Max scaling:")
display(df_diabetes.head())

Applying Min-Max scaling to numerical features of df_diabetes...
Min-Max scaling applied successfully.
First 5 rows of df_diabetes after Min-Max scaling:

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,0.444444,0.670968,0.50000,0.732143,0.527174,0.480499,0.489305,0.637363,1
1,0.074074,0.264516,0.40625,0.517857,0.527174,0.262090,0.243316,0.219780,0
2,0.592593,0.896774,0.37500,0.517857,0.527174,0.159126,0.529412,0.241758,1
3,0.074074,0.290323,0.40625,0.303571,0.000000,0.308892,0.079323,0.000000,0
4,0.000000,0.600000,0.00000,0.732143,1.000000,0.776911,1.000000,0.263736,1

In [ ]:
from sklearn.preprocessing import StandardScaler

print("Applying Standard Scaling to numerical features of df_diabetes...")

# numerical_cols was already defined in the previous step and excludes 'Outcome'
# Re-using numerical_cols from the previous step which was df_diabetes.columns.drop('Outcome')

# Instantiate the StandardScaler
scaler = StandardScaler()

# Apply Standard Scaling to the selected numerical columns in df_diabetes
df_diabetes[numerical_cols] = scaler.fit_transform(df_diabetes[numerical_cols])

print("Standard Scaling applied successfully.")
print("First 5 rows of df_diabetes after Standard Scaling:")
display(df_diabetes.head())

Applying Standard Scaling to numerical features of df_diabetes...
Standard Scaling applied successfully.
First 5 rows of df_diabetes after Standard Scaling:

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,0.647150,0.866045,-0.030632,0.824667,0.039062,0.181092,0.588927,1.445691,1
1,-0.848970,-1.205066,-0.543914,0.017945,0.039062,-0.869465,-0.378101,-0.189304,0
2,1.245598,2.016662,-0.715008,0.017945,0.039062,-1.364728,0.746595,-0.103252,1
3,-0.848970,-1.073567,-0.543914,-0.788777,-1.494110,-0.644346,-1.022787,-1.049828,0
4,-1.148194,0.504422,-2.768136,0.824667,1.414175,1.606849,2.596563,-0.017199,1

## Load Adult Income Dataset

### Subtask:
Download and load the Adult Income dataset into a pandas DataFrame.

In [ ]:
import requests
import pandas as pd

# 1. Download the 'adult.csv' dataset
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data'
response = requests.get(url)

if response.status_code == 200:
    with open('adult.csv', 'wb') as f:
        f.write(response.content)
    print("Adult Income dataset downloaded successfully as 'adult.csv'.")
else:
    print(f"Failed to download Adult Income dataset. Status code: {response.status_code}")

# 2. Define the column names
column_names = [
    'age', 'workclass', 'fnlwgt', 'education', 'education_num', 'marital_status',
    'occupation', 'relationship', 'race', 'sex', 'capital_gain', 'capital_loss',
    'hours_per_week', 'native_country', 'income'
]

# 3. Load the 'adult.csv' file into a pandas DataFrame
df_adult = pd.read_csv('adult.csv', names=column_names, header=None)

print("\nAdult Income dataset loaded into df_adult successfully.")

# 4. Display the first 5 rows
print("First 5 rows of df_adult:")
display(df_adult.head())

Adult Income dataset downloaded successfully as 'adult.csv'.

Adult Income dataset loaded into df_adult successfully.
First 5 rows of df_adult:

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [ ]:
print("1. First 5 rows of df_adult:")
display(df_adult.head())

print("\n2. Information of all columns in df_adult:")
df_adult.info()

print("\n3. Statistical information of numerical columns in df_adult:")
display(df_adult.describe())

print("\n4. Missing values in df_adult:")
display(df_adult.isnull().sum())

1. First 5 rows of df_adult:

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

2. Information of all columns in df_adult:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education_num   32561 non-null  int64
 5   marital_status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital_gain    32561 non-null  int64
 11  capital_loss    32561 non-null  int64
 12  hours_per_week  32561 non-null  int64
 13  native_country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

3. Statistical information of numerical columns in df_adult:

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

4. Missing values in df_adult:

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [ ]:
import numpy as np

print("Handling missing values in df_adult...")

# 1. Identify all columns in df_adult that have an object data type
object_cols = df_adult.select_dtypes(include='object').columns

# 2. For each identified object column, check if the string ' ?' exists as a value.
# If it does, replace all occurrences of ' ?' with np.nan.
for col in object_cols:
    if ' ?' in df_adult[col].unique():
        df_adult[col] = df_adult[col].replace(' ?', np.nan)
        print(f"Replaced ' ?' with NaN in column: {col}")

# 3. After replacing ' ?' with np.nan, display the count of missing values (NaNs)
# for all columns using df_adult.isnull().sum() to confirm the replacement.
print("\nMissing values after replacing ' ?' with NaN:")
display(df_adult.isnull().sum())

# 4. For each column where NaNs were introduced, impute these NaN values using the mode.
for col in object_cols:
    if df_adult[col].isnull().sum() > 0:
        mode_val = df_adult[col].mode()[0] # .mode() returns a Series, take the first element
        df_adult[col] = df_adult[col].fillna(mode_val)
        print(f"Imputed NaN values with mode ({mode_val}) in column: {col}")

# 5. Finally, display the count of missing values again to ensure all NaNs are handled,
# and display the first 5 rows of the updated df_adult DataFrame.
print("\nMissing values after mode imputation:")
display(df_adult.isnull().sum())

print("\nFirst 5 rows of df_adult after handling missing values:")
display(df_adult.head())

Handling missing values in df_adult...
Replaced ' ?' with NaN in column: workclass
Replaced ' ?' with NaN in column: occupation
Replaced ' ?' with NaN in column: native_country

Missing values after replacing ' ?' with NaN:

age                  0
workclass         1836
fnlwgt               0
education            0
education_num        0
marital_status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital_gain         0
capital_loss         0
hours_per_week       0
native_country     583
income               0
dtype: int64

Imputed NaN values with mode ( Private) in column: workclass
Imputed NaN values with mode ( Prof-specialty) in column: occupation
Imputed NaN values with mode ( United-States) in column: native_country

Missing values after mode imputation:

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

First 5 rows of df_adult after handling missing values:

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [ ]:
print("Cleaning and encoding categorical features in df_adult...")

# 1. Identify all columns in df_adult that have an object data type.
object_cols = df_adult.select_dtypes(include='object').columns
print(f"Original object columns: {list(object_cols)}")

# 2. For each identified categorical column, remove any leading or trailing whitespace.
for col in object_cols:
    df_adult[col] = df_adult[col].str.strip()
    print(f"Trimmed whitespace in column: {col}")

# 3. Encode the 'income' column
print("\nEncoding 'income' column...")
income_mapping = {'<=50K': 0, '>50K': 1}
df_adult['income'] = df_adult['income'].map(income_mapping)
print("Value counts of encoded 'income' column:")
display(df_adult['income'].value_counts())

# Remove 'income' from object_cols as it's now numerical
object_cols = object_cols.drop('income', errors='ignore')

# 4. Apply one-hot encoding to the remaining categorical columns
print("\nApplying one-hot encoding to remaining categorical columns...")
df_adult = pd.get_dummies(df_adult, columns=object_cols, drop_first=True)

print("Categorical features encoded successfully.")

# 5. Display the first 5 rows of the updated df_adult DataFrame
print("\nFirst 5 rows of df_adult after categorical encoding:")
display(df_adult.head())

Cleaning and encoding categorical features in df_adult...
Original object columns: ['workclass', 'education', 'marital_status', 'occupation', 'relationship', 'race', 'sex', 'native_country', 'income']
Trimmed whitespace in column: workclass
Trimmed whitespace in column: education
Trimmed whitespace in column: marital_status
Trimmed whitespace in column: occupation
Trimmed whitespace in column: relationship
Trimmed whitespace in column: race
Trimmed whitespace in column: sex
Trimmed whitespace in column: native_country
Trimmed whitespace in column: income

Encoding 'income' column...
Value counts of encoded 'income' column:

income
0    24720
1     7841
Name: count, dtype: int64

Applying one-hot encoding to remaining categorical columns...
Categorical features encoded successfully.

First 5 rows of df_adult after categorical encoding:

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week,income,workclass_Local-gov,workclass_Never-worked,workclass_Private,...,native_country_Portugal,native_country_Puerto-Rico,native_country_Scotland,native_country_South,native_country_Taiwan,native_country_Thailand,native_country_Trinadad&Tobago,native_country_United-States,native_country_Vietnam,native_country_Yugoslavia
0,39,77516,13,2174,0,40,0,False,False,False,...,False,False,False,False,False,False,False,True,False,False
1,50,83311,13,0,0,13,0,False,False,False,...,False,False,False,False,False,False,False,True,False,False
2,38,215646,9,0,0,40,0,False,False,True,...,False,False,False,False,False,False,False,True,False,False
3,53,234721,7,0,0,40,0,False,False,True,...,False,False,False,False,False,False,False,True,False,False
4,28,338409,13,0,0,40,0,False,False,True,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
import numpy as np

print("Handling outliers in df_adult...")

# 1. Identify numerical columns, excluding 'income'
# The 'income' column was already transformed into numerical (0 or 1) and is the target variable.
# Other columns are either numerical (age, fnlwgt, education_num, capital_gain, capital_loss, hours_per_week)
# or one-hot encoded binary columns, which typically aren't treated for outliers in this manner.

numerical_cols_for_outliers = [
    'age', 'fnlwgt', 'education_num', 'capital_gain', 'capital_loss', 'hours_per_week'
]

# 2-6. Calculate IQR and cap outliers for each identified numerical column
for col in numerical_cols_for_outliers:
    Q1 = df_adult[col].quantile(0.25)
    Q3 = df_adult[col].quantile(0.75)
    IQR = Q3 - Q1

    upper_bound = Q3 + 1.5 * IQR
    lower_bound = Q1 - 1.5 * IQR

    # Cap the outliers
    df_adult[col] = np.where(df_adult[col] > upper_bound, upper_bound, df_adult[col])
    df_adult[col] = np.where(df_adult[col] < lower_bound, lower_bound, df_adult[col])
    print(f"Outliers capped for column: {col}")

print("Outliers handled successfully using IQR capping for specified numerical columns.")

# 7. Display the first 5 rows of df_adult after outlier handling
print("\nFirst 5 rows of df_adult after outlier handling:")
display(df_adult.head())

Handling outliers in df_adult...
Outliers capped for column: age
Outliers capped for column: fnlwgt
Outliers capped for column: education_num
Outliers capped for column: capital_gain
Outliers capped for column: capital_loss
Outliers capped for column: hours_per_week
Outliers handled successfully using IQR capping for specified numerical columns.

First 5 rows of df_adult after outlier handling:

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week,income,workclass_Local-gov,workclass_Never-worked,workclass_Private,...,native_country_Portugal,native_country_Puerto-Rico,native_country_Scotland,native_country_South,native_country_Taiwan,native_country_Thailand,native_country_Trinadad&Tobago,native_country_United-States,native_country_Vietnam,native_country_Yugoslavia
0,39.0,77516.0,13.0,0.0,0.0,40.0,0,False,False,False,...,False,False,False,False,False,False,False,True,False,False
1,50.0,83311.0,13.0,0.0,0.0,32.5,0,False,False,False,...,False,False,False,False,False,False,False,True,False,False
2,38.0,215646.0,9.0,0.0,0.0,40.0,0,False,False,True,...,False,False,False,False,False,False,False,True,False,False
3,53.0,234721.0,7.0,0.0,0.0,40.0,0,False,False,True,...,False,False,False,False,False,False,False,True,False,False
4,28.0,338409.0,13.0,0.0,0.0,40.0,0,False,False,True,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
from sklearn.preprocessing import MinMaxScaler

print("Applying Min-Max scaling to numerical features of df_adult...")

# 1. Define a list of numerical columns to be scaled.
# These are the same columns identified for outlier handling.
numerical_cols_for_scaling = [
    'age', 'fnlwgt', 'education_num', 'capital_gain', 'capital_loss', 'hours_per_week'
]

# 2. Instantiate a MinMaxScaler object.
scaler = MinMaxScaler()

# 3. Apply Min-Max scaling to the selected numerical columns in df_adult
df_adult[numerical_cols_for_scaling] = scaler.fit_transform(df_adult[numerical_cols_for_scaling])

print("Min-Max scaling applied successfully.")

# 4. Display the first 5 rows of the updated df_adult DataFrame
print("First 5 rows of df_adult after Min-Max scaling:")
display(df_adult.head())

Applying Min-Max scaling to numerical features of df_adult...
Min-Max scaling applied successfully.
First 5 rows of df_adult after Min-Max scaling:

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week,income,workclass_Local-gov,workclass_Never-worked,workclass_Private,...,native_country_Portugal,native_country_Puerto-Rico,native_country_Scotland,native_country_South,native_country_Taiwan,native_country_Thailand,native_country_Trinadad&Tobago,native_country_United-States,native_country_Vietnam,native_country_Yugoslavia
0,0.360656,0.161622,0.739130,0.0,0.0,0.375,0,False,False,False,...,False,False,False,False,False,False,False,True,False,False
1,0.540984,0.175980,0.739130,0.0,0.0,0.000,0,False,False,False,...,False,False,False,False,False,False,False,True,False,False
2,0.344262,0.503865,0.391304,0.0,0.0,0.375,0,False,False,True,...,False,False,False,False,False,False,False,True,False,False
3,0.590164,0.551127,0.217391,0.0,0.0,0.375,0,False,False,True,...,False,False,False,False,False,False,False,True,False,False
4,0.180328,0.808034,0.739130,0.0,0.0,0.375,0,False,False,True,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
from sklearn.preprocessing import StandardScaler

print("Applying Standard Scaling to numerical features of df_adult...")

# numerical_cols_for_scaling was already defined in the previous step
# It contains: ['age', 'fnlwgt', 'education_num', 'capital_gain', 'capital_loss', 'hours_per_week']

# Instantiate the StandardScaler
scaler = StandardScaler()

# Apply Standard Scaling to the selected numerical columns in df_adult
df_adult[numerical_cols_for_scaling] = scaler.fit_transform(df_adult[numerical_cols_for_scaling])

print("Standard Scaling applied successfully.")
print("First 5 rows of df_adult after Standard Scaling:")
display(df_adult.head())

Applying Standard Scaling to numerical features of df_adult...
Standard Scaling applied successfully.
First 5 rows of df_adult after Standard Scaling:

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week,income,workclass_Local-gov,workclass_Never-worked,workclass_Private,...,native_country_Portugal,native_country_Puerto-Rico,native_country_Scotland,native_country_South,native_country_Taiwan,native_country_Thailand,native_country_Trinadad&Tobago,native_country_United-States,native_country_Vietnam,native_country_Yugoslavia
0,0.032782,-1.149114,1.169103,0.0,0.0,-0.194354,0,False,False,False,...,False,False,False,False,False,False,False,True,False,False
1,0.844236,-1.088196,1.169103,0.0,0.0,-1.406591,0,False,False,False,...,False,False,False,False,False,False,False,True,False,False
2,-0.040986,0.302927,-0.457091,0.0,0.0,-0.194354,0,False,False,True,...,False,False,False,False,False,False,False,True,False,False
3,1.065541,0.503446,-1.270187,0.0,0.0,-0.194354,0,False,False,True,...,False,False,False,False,False,False,False,True,False,False
4,-0.778671,1.593428,1.169103,0.0,0.0,-0.194354,0,False,False,True,...,False,False,False,False,False,False,False,False,False,False